# Generated by Django 4.1.3 on 2022-11-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_puestos_jefatura_empleados_jefatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.entidades'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='municipio',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
    ]
